---
- name: Install web server and add line to index.html file on all app servers
  hosts: all
  become: true
  tasks:
    - name: install web server
      yum: 
        name: httpd
        state: present
    - name: Ensure httpd service is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
    - name: create index.html
      copy:
        dest: /var/www/html/index.html
        content: "This is a Nautilus sample file, created using Ansible!"
        owner: apache
        group: apache
        mode: '0777'
    - name: Add lines on the top of the file
      lineinfile: 
        path: /var/www/html/index.html
        insertbefore: BOF
        line: "Welcome to xFusionCorp Industries!"
