---
- name: Copy files based on hostname
  hosts: all
  become: yes
  tasks:
    - name: Copy file on stapp01
      copy:
        src: /usr/src/itadmin/blog.txt
        dest: /opt/itadmin
        owner: tony
        group: tony
        mode: 0744
      when: inventory_hostname == "stapp01"

    - name: Copy file on stapp02
      copy:
        src: /usr/src/itadmin/story.txt
        dest: /opt/itadmin
        owner: steve
        group: steve
        mode: 0744
      when: inventory_hostname == "stapp02"

    - name: Copy file on stapp03
      copy:
        src: /usr/src/itadmin/media.txt
        dest: /opt/itadmin
        owner: banner
        group: banner
        mode: 0744
      when: inventory_hostname == "stapp03"
